// auth
export const USER_LOGIN = 'USER_LOGIN'
export const CREATE_USER = 'CREATE_USER'
export const AUTH_ERROR = 'AUTH_ERROR'
export const AUTH_LOADING = 'AUTH_LOADING'
export const USER_LOGOUT = 'USER_LOGOUT'
export const RESET_EMAIL_SENT = 'RESET_EMAIL_SENT'
export const PASSWORD_RESET = 'PASSWORD_RESET'
export const CHECK_AUTH_FAIL = 'CHECK_AUTH_FAIL'
export const VERIFY_EMAIL = 'VERIFY_EMAIL'

// profile
export const PROFILE_LOADING = 'PROFILE_LOADING'
export const PROFILE_ERROR = 'PROFILE_ERROR'
export const SET_PROFILE = 'SET_PROFILE'

// sell
export const ORDERS_LOADING = 'ORDERS_LOADING'
export const ORDERS_INITIAL_LOADING = 'ORDERS_INITIAL_LOADING'
export const GET_ORDERS_ERROR = 'GET_ORDERS_ERROR'
export const SET_ORDERS = 'SET_ORDERS'
export const CLAIM_ORDER = 'CLAIM_ORDER'
export const CLAIM_ORDER_LOADING = 'CLAIM_ORDER_LOADING'
export const CLAIM_ORDER_ERROR = 'CLAIM_ORDER_ERROR'
export const UNCLAIM_ORDER = 'UNCLAIM_ORDER'
