// auth
export const USER_LOGIN = 'USER_LOGIN'
export const CREATE_USER = 'CREATE_USER'
export const AUTH_ERROR = 'AUTH_ERROR'
export const AUTH_LOADING = 'AUTH_LOADING'
export const USER_LOGOUT = 'USER_LOGOUT'
export const RESET_EMAIL_SENT = 'RESET_EMAIL_SENT'
export const PASSWORD_RESET = 'PASSWORD_RESET'
export const CHECK_AUTH_FAIL = 'CHECK_AUTH_FAIL'
export const VERIFY_EMAIL = 'VERIFY_EMAIL'

// profile
export const PROFILE_LOADING = 'PROFILE_LOADING'
export const PROFILE_ERROR = 'PROFILE_ERROR'
export const SET_PROFILE = 'SET_PROFILE'
export const DELETE_PROFILE_ERROR = 'DELETE_PROFILE_ERROR'

// meal
export const MEAL_ERROR = 'MEAL_ERROR'
export const SET_MEAL_DATA = 'SET_MEAL_DATA'
export const SET_RESTAURANT_DATA = 'SET_RESTAURANT_DATA'
export const MEAL_LOADING = 'MEAL_LOADING'

// order
export const SET_RESTAURANT = 'SET_RESTAURANT'
export const SET_ENTREE = 'SET_ENTREE'
export const SET_ENTREE_CUSTOMIZATIONS = 'SET_ENTREE_CUSTOMIZATIONS'
export const SET_SIDE = 'SET_SIDE'
export const SET_SIDE_CUSTOMIZATIONS = 'SET_SIDE_CUSTOMIZATIONS'
export const SET_DRINK = 'SET_DRINK'
export const SET_SAUCE = 'SET_SAUCE'
export const SET_PICKUP_TIME = 'SET_PICKUP_TIME'
export const ORDER_ERROR = 'ORDER_ERROR'
export const ORDER_LOADING = 'ORDER_LOADING'
export const ORDER_PLACED = 'ORDER_PLACED'
export const ORDER_CANCELLED = 'ORDER_CANCELLED'
export const CLEAR_ORDER = 'CLEAR_ORDER'

// sell
export const ORDERS_LOADING = 'ORDERS_LOADING'
export const ORDERS_INITIAL_LOADING = 'ORDERS_INITIAL_LOADING'
export const GET_ORDERS_ERROR = 'GET_ORDERS_ERROR'
export const SET_ORDERS = 'SET_ORDERS'
export const CLAIM_ORDER = 'CLAIM_ORDER'
export const CLAIM_ORDER_LOADING = 'CLAIM_ORDER_LOADING'
export const CLAIM_ORDER_ERROR = 'CLAIM_ORDER_ERROR'
export const UNCLAIM_ORDER = 'UNCLAIM_ORDER'
export const CONFIRM_ORDER = 'CONFIRM_ORDER'

// payment
export const CLEAR_PAYMENT_SETUP = 'CLEAR_PAYMENT_SETUP'
export const PAYMENT_LOADING = 'PAYMENT_LOADING'
export const PAYMENT_ERROR = 'PAYMENT_ERROR'
export const SET_PAYMENT_METHODS = 'SET_PAYMENT_METHODS'
export const SET_PAYMENT_SETUP = 'SET_PAYMENT_SETUP'

// payout
export const CLEAR_PAYOUT_SETUP = 'CLEAR_PAYOUT_SETUP'
export const PAYOUT_LOADING = 'PAYOUT_LOADING'
export const PAYOUT_ERROR = 'PAYOUT_ERROR'
export const SET_PAYOUT_METHODS = 'SET_PAYOUT_METHODS'
export const SET_PAYOUT_SETUP = 'SET_PAYOUT_SETUP'

// push tokens
export const SET_PUSH_TOKEN = 'SET_PUSH_TOKEN'
export const SET_PUSH_TOKEN_ERROR = 'SET_PUSH_TOKEN_ERROR'
export const SET_PUSH_TOKEN_LOADING = 'SET_PUSH_TOKEN_LOADING'
